const data = {
  product: [
    {
      name: 'Nike Jordan 80',
      slug: 'nike-jordan-80',
      category: 'Shoes',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Jumbo Jordan 80',
      slug: 'jumbo-jordan-80',
      category: 'Shirt',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Jumbo',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Puma Jordan 80',
      slug: 'puma-jordan-80',
      category: 'Shoes',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Jordan 80',
      slug: 'adidas-jordan-80',
      category: 'Shoes',
      image: '/images/p4.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
  ],
};

export default data